
- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  register: root_password

- name: Generate chrootpw file
  template: src=chrootpw.j2 dest={{ openldap_tmp_files_ldif }}/chrootpw.ldif

- name: Add chrootpw to ldap
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap_tmp_files_ldif }}/chrootpw.ldif

- name: Add schema cosine
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif

- name: Add schema nis
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif

- name: Add schema inetorgperson
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

- name: Generate chdomain file
  template: src=chdomain.j2 dest={{ openldap_tmp_files_ldif }}/chdomain.ldif

- name: Add chdomain.ldif file to ldap 
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap_tmp_files_ldif }}/chdomain.ldif

- name: Generate basedomain file
  template: src=basedomain.j2 dest={{ openldap_tmp_files_ldif }}/basedomain.ldif

- name: Add chdomain.ldif file to ldap 
  shell: ldapadd -x -D cn=Manager,dc={{ openldap_server_domain_name.split('.')[0] }},dc={{ openldap_server_domain_name.split('.')[1] }} -w {{ openldap_server_rootpw }} -f {{ openldap_tmp_files_ldif }}/basedomain.ldif

- name: Create users file
  template: src=users.j2 dest={{ openldap_tmp_files_ldif }}/users.ldif

- name: Add users.ldif file to ldap 
  shell: ldapadd -x -D cn=Manager,dc={{ openldap_server_domain_name.split('.')[0] }},dc={{ openldap_server_domain_name.split('.')[1] }} -w {{ openldap_server_rootpw }} -f {{ openldap_tmp_files_ldif }}/users.ldif
  