
- name: Generate file for import certificates
  template: src=certs.j2 dest={{ openldap_tmp_files_ldif }}/certs.ldif

- name: Add certs.ldif to ldap
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ openldap_tmp_files_ldif }}/certs.ldif
  become: true

- name: Add ca.pem to /etc/openldap/ldap.conf
  lineinfile:
    path: /etc/openldap/ldap.conf
    regexp: 'TLS_CACERTDIR'
    line: TLS_CACERTDIR {{ openldap_certificates_path }}/ca.pem
  become: true