
- name: Generate file for import certificates
  template: src=certs.j2 dest={{ openldap_tmp_files_ldif }}/certs.ldif

- name: Add certs.ldif to ldap
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f {{ openldap_tmp_files_ldif }}/
  become: true
