- name: Install packages needed (PHP, HTTPD, PHP-LDAP, MOD_SSL)
  yum:
    name:
      - httpd
      - php
      - php-ldap
      - mod_ssl
      
    state: installed

- name: Download phpLDAPadmin from Sirepo and move to /usr/share/phpldapadmin
  unarchive:
    src: https://sirepo.s3-eu-west-1.amazonaws.com/phpldapadmin.zip
    dest: /usr/share/
    remote_src: yes
    owner: "apache"
    group: "apache"

- name: Create config file phpldapadmin
  copy:
    src: /usr/share/phpldapadmin/config/config.php.example
    dest: /usr/share/phpldapadmin/config/config.php
    owner: "apache"
    group: "apache"

- name: Create phpdlapadmin.conf en httpd
  copy:
    src: ./files/phpldapadmin.conf
    dest: /etc/httpd/conf.d/phpldapadmin.conf
    owner: "apache"
    group: "apache"

- name: Ensure the default Apache port is 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 8080

- name: Enable HTTPD SSL (server.pem)
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: 'SSLCertificateFile /etc/pki/tls/certs/localhost.crt'
    #insertafter: 'SSLCertificateFile'
    line: SSLCertificateFile {{ certs_path }}/server.pem

- name: Enable HTTPD SSL certs (server_key2.pem)
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: 'SSLCertificateKeyFile /etc/pki/tls/private/localhost.key'
    #insertafter: 'SSLCertificateKeyFile'
    line: SSLCertificateKeyFile {{ certs_path }}/server_key2.pem

- name: Enable HTTPD SSL certs (ca.pem)
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '#SSLCertificateChainFile'
    #insertafter: '#SSLCertificateChainFile'
    line: SSLCertificateChainFile /home/julian/certs/ldap-cert/ca.pem

- name: Enable Virtual Host on port 8080
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '<VirtualHost _default_:443>'
    #insertafter: '<VirtualHost _default_:443>'
    line: <VirtualHost _default_:8080>

- name: Enable service httpd, and start it
  service:
    name: httpd
    state: started
    enabled: yes
   