- name: Stop httpd service
  service:
    name: httpd
    state: stopped
  ignore_errors: yes
  become: true

- name: Remove packages installed (PHP, HTTPD, PHP-LDAP, MOD_SSL)
  package:
    name:
      - httpd
      - php
      - php-ldap
      - mod_ssl
    state: absent
    autoremove: true
  become: true

- name: Remove /usr/share/phpldapadmin
  file:
    state: absent
    path: "/usr/share/phpldapadmin/"
  become: true

- name: Remove /etc/httpd
  file:
    state: absent
    path: "/etc/httpd/"
  become: true

  