
- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }} 
  register: root_password

- name: Generar chroot file
  template: src=chrootpw.j2 dest={{ openldap_tmp_files_ldif }}/chroot.ldif

- name: Add chrootpw to ldap
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap_tmp_files_ldif }}/chrootpw.ldif

- name: Add schema cosine
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif

- name: Add schema nis
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif

- name: Add schema inetorgperson
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

